version: '3.4'
services:
  cer-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    environment:
      - SN_BASE_URL
      - SN_USER
      - SN_PASSWORD
      - SN_API_KEY
      - SN_REQUESTS_CONFIG_FILE
      - https_proxy
    volumes:
      - ${HUB_PATH}/config/cer-api/requests-config.json:/requests-config.json
