version: '3.0'
services:
  cer-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    environment:
      - SN_BASE_URL
      - SN_USER
      - SN_PASSWORD
      - SN_REQUESTS_CONFIG_FILE
      - https_proxy
